# Generated by Django 3.2 on 2021-05-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_persone_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='parent_subdivision',
            new_name='parent',
        ),
    ]
